version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    container_name: container_teslo
    environment:
      # POSTGRES_USER: ${DB_PASSWORD}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
